server:
  port: 8084

spring:
  application:
    name: API-GATEWAY


  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/staffs/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**




eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#okta configuration for api gateway

okta:
  oauth2:
    issuer: https://dev-57872596.okta.com/oauth2/default
    audience: api://default
    client-id: 0oagvt6y7bzZOb4HN5d7
    client-secret: 5S6y_nb4xeE3JPRpCvSHEooqCJzSFH1S11qpfW8lWkSPoqzjMbRnZo8Yg_6YcoUq
    scopes: openid, profile, email, offline_access